# Generated by Django 4.1.5 on 2023-01-24 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_rename_image_profile_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_image',
            new_name='image',
        ),
    ]
